#!/bin/sh
if [ `id -u` -eq "0" ]; then
    echo "Running the Webbrowser as root is not encouraged."
    echo "Aborting."
    exit 1;
fi

xhost +local:

if [ -x /usr/local/bin/doas ]; then
        doas /usr/local/libexec/jail-librewolf-exec $1
elif [ -x /usr/local/bin/sudo ]; then
        doas /usr/local/libexec/jail-librewolf-exec $1
else
    echo "Need either security/doas or security/sudo to proceed."
fi


